### ISSUE TITLE
Formulario de contacto

### ISSUE THREAD

**Issue by merRen22** [RPG-Devs/landing#3]
Debe ir en el área de contacto 

Boton de contactanos debe llevar a area de registrarse

Campos:

(Misma lógica que web Contacts de Ciqnui)
Nombre / Full name
Telefono / Phone Number
Correo / Email
Empresa / Business
¿Cómo podemos ayudarte? / How can we help?

Agregar un Captcha o algo para que no hagan llenado masivo con un bot.

**Comment by merRen22** [comment]
@gabosh140 ponemos el area de "contact". Antes de nuestro aliados y despues de "Por que RPG"?

**Comment by gabosh140** [comment]
Despues

**Comment by merRen22** [comment]
El formulario debera enviar la data en JSON a https://jsonsilo.com/

Las credencials se pasaran por interno
